# Generated by Django 4.0.5 on 2022-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=3000, verbose_name='Задача')),
                ('date_of_completion', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
