# Generated by Django 4.0.5 on 2022-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status_t',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_of_completion',
            field=models.DateField(verbose_name='Дата выполнения'),
        ),
    ]
