# Generated by Django 4.0.5 on 2022-06-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_tasks_status_t_alter_tasks_date_of_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default=True, max_length=2500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=30, verbose_name='Задача'),
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
    ]
