# Generated by Django 4.0.5 on 2022-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_tasks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(max_length=2500, verbose_name='Описание'),
        ),
    ]
